name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Updating server via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.API_URL }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.API_DDP }}
          script: source /home/admin/.nvm/nvm.sh && ~/bin/deploy-duckduckpatent.bash